### ISSUE TITLE
cpp-primer_ch9_Exercise 9.12

### ISSUE THREAD

**Issue by Ocxs** [Ocxs/Issues#3]
> we can use the constructor that takes two iterators to copy a subsequence of a container. But the constructor that takes a container to copy should copy whole container.

@pezy @Mooophy 这里的意思应该是用迭代器是只拷贝迭代器之间的元素，用容器必须拷贝整个容器的元素吧？这个词组**whole container**我觉得是不是有点不恰当呢？因为我第一次读这个答案，我的第一反应是整个容器，那是不是还要包括容器除其元素以外的的迭代器等一切东西都要拷贝？实际上好像要表达的意思是拷贝整个容器的元素，仅此而已（其他东西好像向拷贝也拷贝不了吧）

那答案这样修改一下是不是更好：
接受一个容器创建其拷贝的构造函数**拷贝整个容器的元素**，接受两个迭代器创建拷贝的构造函数**只能拷贝两个迭代器之间的元素（这里的元素范围应该是**左闭合区间**）。左闭合区间：[begin,end)**

额，以上只是我个人的一点愚见，不知道理解的对不对，当然可能其他人第一眼看到没有我这样的错觉（毕竟我这英语太渣）。（ps.当我知道其中的意思之后，发现英语描述好像就没毛病了，没看懂之前感觉就是我之前在上面说的错觉）

**Comment by pezy** [comment]
@Ocxs 这个问题看来是我的英语太渣了。。。

拷贝一下这道题的题目：

>Exercise 9.12:

>Explain the differences between the constructor that takes a container to copy and the constructor that takes two iterators.

而我想回答的是：不同点在于，用两个迭代器作为参数，可以拷贝该容器的子序列；而用容器作为参数，则只能选择拷贝整个容器。

例如：

```cpp
std::vector<int> vec{1,2,3,4,5};
std::vector<int> vec1(std::next(vec.begin()), std::prev(vec.end())); // 2,3,4
std::vector<int> vec2(vec); // 1,2,3,4,5
```

**Comment by Ocxs** [comment]
@pezy 看来我理解的没错了  :smile:

**Comment by pezy** [comment]
@Ocxs 我觉得没啥问题，英语那个答案看 @Mooophy 有无意见吧。。

另：接下来几章，都很简单，可以适当的加快进度了。

**Comment by Ocxs** [comment]
@pezy 我理解之后觉得没啥问题，没理解之前觉得有问题，哈哈。我尽量加快，毕竟还要上课啊，我都大三了，要是早点上了知乎就好了啊，早看了那些指导，说不定我就早些看C++primer了

**Comment by pezy** [comment]
@Ocxs 也不用着急，就是提前告诉你 9，10，11 三章，你会看起来非常爽，我估计很难遇到不懂的地方。到 12 和 13 章，估计你的问题又该多起来了。（可能不一样，我在此预测一下）。

开始还以为你大一、大二，大三的话，应该有很多重要的专业课了吧？如算法、组成原理、OS、网络之类。相比之下，还是那些重要。C++ 只是一个语言工具，空余时间坚持把这本书看完就行了。

这本书，我是上班后才看的，时间肯定还不如你多，看的也比你慢的多得多。。。

你该庆幸自己还在大学，完全来得及~

**Comment by Ocxs** [comment]
@pezy 我这一章也有不少问题，准备习题做完之后看能不能自己搞懂，搞不懂再贴上来问，您说的那些课程，如算法、编译原理，组成原理、OS、网络之类我都上完了（不过学的一般啊，虽然考试还行，:cry:)     。这学期课程不是特别多。:smile: 我现在有时候还是挺疑惑到底该不该读研究生的。

**Comment by pezy** [comment]
@Ocxs 毫无疑问啊，有条件当然读研究生。。。

**Comment by Mooophy** [comment]
意思是没问题的，英文措辞有点儿小问题，可以改为：
* Constructor that takes two iterators copy the items between the range `[first, last)`,e.g.
```cpp
auto data = {1,2,3};
std::vector<int> vec(data.begin(), data.begin()+1); // vec is {1}
```
* Constructor that takes another container copy all items from it.
e.g.
```cpp
auto data = {1,2,3};
std::vector<int> vec(data); //vec is {1,2,3}
```

**Comment by Mooophy** [comment]
"to copy"这个不定式有点儿累赘，第二句里的情态动词"should"用的比较奇怪。。
我怀疑我第一版的答案里措辞就有问题。。

**Comment by Mooophy** [comment]
@Ocxs 的问题挺有深度的，个人看法是：container(容器)这个词是指抽象数据类型，或者说是抽象数据结构, 也就是ADT([wiki](http://en.wikipedia.org/wiki/Abstract_data_type))：
>In computer science, an abstract data type (ADT) is a **mathematical model** for a certain class of data structures that have similar behaviour; or for certain data types of one or more programming languages that have similar semantics. An abstract data type is defined only **by the operations that may be performed on it and by mathematical pre-conditions and constraints on the effects (and possibly cost) of those operations**. 

所以不用考虑迭代器等实现细节层面的东西。

**Comment by Ocxs** [comment]
@pezy 为什么呢？（我待会在知乎上私信你一下，求讲解）

**Comment by Ocxs** [comment]
@Mooophy 贴的wiki看的我似懂非懂啊 :sob:

**Comment by Mooophy** [comment]
哦，那个跟当前话题也不是很相关。。不用去管了。 @Ocxs

**Comment by Mooophy** [comment]
算了，还是解释一下吧。针对你这句话：
>我的第一反应是整个容器，那是不是还要包括容器除其元素以外的的迭代器等一切东西都要拷贝？

我贴这段的意思是说：
当我们提到container或者容器的时候，是指抽象数据结构，不包含其内部的实现细节。迭代器就属于实现细节层面的。所以，当我们说copy 一个 container的时候，往往是忽略元素以外的东西的。

**Comment by Mooophy** [comment]
再让一步，就算特指STL容器，迭代器也不一定就是容器的一部分。STL倡导并实现了容器和迭代器分离，在后续阅读中会反复体验的。

**Comment by Ocxs** [comment]
@Mooophy 非常感谢！等我学完这些内容我在好好体会一下！ :smile:
