### ISSUE TITLE
cpp-primer_ch9_Exercise 9.29

### ISSUE THREAD

**Issue by Ocxs** [Ocxs/Issues#4]
>  ```cpp
vec.resize(100);    // adds 75 elements of value 0 to the back of vec
vec.resize(10);     // erases 90 elements from the back of vec
```

这里的答案给的是在vec后面添加75个值为0的元素，我觉得这好像有点不严谨，因为这里没说vector里的元素是什么类型，（按照c++primer默认的风格，ivec应该是默认int型的vector，但是这里只写了vec）
然后我自己准备解决这个问题，commit的，但是遇到点小问题。
本来补充的答案：
adds 75 elements to the back of vec,if the type of elements is built-in type,in this case the library creates a value-initialized element initializer for us.This library-generated value is used to initialize each element in the container.If the type of elements is class type,it will call default constructor to initialize the elements.(Here we think that it has default constructor,otherwise it's wrong.）
然后本着严谨的原则，我在想要这里的class-type应该要补充一下它有默认构造函数才行。resize(100)肯定会调用默认构造函数。（这一点在书上说了，在7.1.4构造函数--定义Sales_data的构造函数里说：
>  An empty parameter list (i.e., the default constructor) which as we’ve just seen we ** must ** define because we have defined other constructors.

我的疑问是：按照书上的意思，好像只要定义了其他构造函数就一定要定义默认构造函数，我想知道这里的must是作者为了让大家提高严谨的态度才写成必须呢？还是就是要这样写呢？难道我每次创建新的对象的时候我都会主动传参数进去，这样不就没有用到默认构造参数了吗？但是我测试的时候发现，不加默认构造函数的话，也ok。

还是举个例子说比较好一点：
```cpp
class A
{
public：
      A(int i){}
}

vector<A> vec(25,A(3));//我觉得这样写没有问题，实际也没有报错
```
不知道我理解的对不对，写在这里给你们二位@pezy @Mooophy 判断一下，如果对的话，我周五给他整理一下啊。(@pezy 我在另外一个问题也给你@了，因为那个问题跟这个问题，也有那么一点管理，也就一并贴上，方便别人观看[那个问题](https://github.com/Ocxs/Cpp-Primer/issues/4)

**Comment by Mooophy** [comment]
目前的答案的确有问题。如 @Ocxs 所说， 题目中没有暗示`vec`就是`std::vector<int>`。可改为：
`adds 75 items to the back of vec. added elements are  value initialized`.

**Comment by Mooophy** [comment]
我的理解，此处的must的含义是：如果不自定义default constructor的话，compiler是不会为我们生成的。作者是为了提醒读者：这是一个重要知识点。实际开发中，default constructor 和任一类型的constructor一样，是根据需求来决定是否定义的。比如下述代码会报错，因为`std::istream`没有提供default constructor。

```cpp
#include <istream>
int main()
{
	std::istream is;
	return 0;
}
```

**Comment by Mooophy** [comment]
再比如你想定义一个class叫`Student`，该class里提供`public`的数据成员，又要防止外部代码不小心改动该成员，就可以写成这样：
```cpp
class Student
{
public:
	Student() = delete;//no student has no name, so no default constructor has been defined.

	Student(std::string nm, int id)
		: name(nm), student_id(id)
	{}

	const std::string name;
	const int student_id;
};
```
此处用`delete`显性提醒class的用户：该class不提供default constructor。

**Comment by Mooophy** [comment]
总结：是否定义default constructor是由实际需求决定的，此处的must是对知识点的提醒。

**Comment by Mooophy** [comment]
事实上， @Ocxs 的疑惑是因为对内存和OO的理解深度不够造成的。暂时不要去管那个must，换个角度想问题。
假设有class如下：
```cpp
#include <iostream>

class Box
{
public:
	Box() = default;

	Box(int thg, long cvr)
		: thing(thg), cover(cvr)
	{}

	int thing;
	long cover;
};

int main()
{
	Box box;
	std::cout << box.thing << std::endl;
	return 0;
}
```
对象box的内存布局（原理上）是这样的：
```cpp
{ [thing] | [cover] }
```
可以想象成一个盒子装了俩东西：thing和cover。那么constructor的功能就是:提供一个创造盒子的方案。
* 对于default constructor而言，相当于创建box的时候，不传递参数进去，constructor自己去构建这个box。
* 对于非default constructor而言，相当于创建box的时候，传递参数进去，从而创建这个box。
但无论创建box的时候你用哪种constrcutor，box的（原理性）内存布局都是一样的。

**Comment by pezy** [comment]
同意 @Mooophy 的讲解。

简单就一句：**自定义构造会覆盖默认构造，如需默认构造，需显式定义之**。

如你的例子，对于 `vector<A> vec` 来说，加一句:

```cpp
vec.resize(100);
```

就歇菜。

**Comment by Ocxs** [comment]
@Mooophy @pezy 谢谢二位，其中@Mooophy 的那个盒子那个例子加深了我的理解，非常感谢！:+1:
