### ISSUE TITLE
chapter10_quesiton2_ex10_10

### ISSUE THREAD

**Issue by Ocxs** [Ocxs/Issues#6]
@pezy: Cause the library algorithms operate on iterators, not containers. Thus, an algorithm cannot (directly) add or remove elements.

@pezy 赞同你的答案，我想的是很多库里实现算法的函数接受的参数多是迭代器，所以一旦改变容器大小可能会造成迭代器失效，导致函数运行的过程出现未知情况，我觉得你应该就是这个意思吧？（这里说容器大小是不是不严谨？不知道指的是size还是capacity？，还是说中文中有约定的说法？）

**Comment by pezy** [comment]
我的意思是，algorithms 库眼里只有 iterators，没有 containers。所以它无法直接增删容器里的元素，也就无法直接改变容器的 size 了。

至于：
> 我想的是很多库里实现算法的函数接受的参数多是迭代器，所以一旦改变容器大小可能会造成迭代器失效

我觉得这并非主要原因，采用迭代器，我觉得更多的是为泛型考虑。（改变容器大小后，有很多办法让迭代器恢复）

**Comment by Ocxs** [comment]
@pezy thx！:smile:
